package com.gwytest.entity;
// Generated 2016-5-5 2:54:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbBbs generated by hbm2java
 */
public class TbBbs implements java.io.Serializable {

	private int bbsid;
	private TbUser tbUser;
	private String bbstitle;
	private String bbscontent;
	private Date bbstime;

	public TbBbs() {
	}

	public TbBbs(int bbsid, TbUser tbUser, String bbstitle, String bbscontent, Date bbstime) {
		this.bbsid = bbsid;
		this.tbUser = tbUser;
		this.bbstitle = bbstitle;
		this.bbscontent = bbscontent;
		this.bbstime = bbstime;
	}

	public int getBbsid() {
		return this.bbsid;
	}

	public void setBbsid(int bbsid) {
		this.bbsid = bbsid;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public String getBbstitle() {
		return this.bbstitle;
	}

	public void setBbstitle(String bbstitle) {
		this.bbstitle = bbstitle;
	}

	public String getBbscontent() {
		return this.bbscontent;
	}

	public void setBbscontent(String bbscontent) {
		this.bbscontent = bbscontent;
	}

	public Date getBbstime() {
		return this.bbstime;
	}

	public void setBbstime(Date bbstime) {
		this.bbstime = bbstime;
	}

}
