package com.gwytest.entity;
// Generated 2016-5-5 2:54:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbTitle generated by hbm2java
 */
public class TbTitle implements java.io.Serializable {

	private int titleid;
	private String rightselect;
	private String analysis;
	private String subjectname;
	private String testname;
	private String titlename;
	private String a;
	private String b;
	private String c;
	private String d;
	private Date savetime;
	private Set tbComments = new HashSet(0);
	private Set tbUsertitles = new HashSet(0);

	public TbTitle() {
	}

	public TbTitle(int titleid, String rightselect, String subjectname, String testname, Date savetime) {
		this.titleid = titleid;
		this.rightselect = rightselect;
		this.subjectname = subjectname;
		this.testname = testname;
		this.savetime = savetime;
	}

	public TbTitle(int titleid, String rightselect, String analysis, String subjectname, String testname,
			String titlename, String a, String b, String c, String d, Date savetime, Set tbComments, Set tbUsertitles) {
		this.titleid = titleid;
		this.rightselect = rightselect;
		this.analysis = analysis;
		this.subjectname = subjectname;
		this.testname = testname;
		this.titlename = titlename;
		this.a = a;
		this.b = b;
		this.c = c;
		this.d = d;
		this.savetime = savetime;
		this.tbComments = tbComments;
		this.tbUsertitles = tbUsertitles;
	}

	public int getTitleid() {
		return this.titleid;
	}

	public void setTitleid(int titleid) {
		this.titleid = titleid;
	}

	public String getRightselect() {
		return this.rightselect;
	}

	public void setRightselect(String rightselect) {
		this.rightselect = rightselect;
	}

	public String getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}

	public String getSubjectname() {
		return this.subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	public String getTestname() {
		return this.testname;
	}

	public void setTestname(String testname) {
		this.testname = testname;
	}

	public String getTitlename() {
		return this.titlename;
	}

	public void setTitlename(String titlename) {
		this.titlename = titlename;
	}

	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	public String getB() {
		return this.b;
	}

	public void setB(String b) {
		this.b = b;
	}

	public String getC() {
		return this.c;
	}

	public void setC(String c) {
		this.c = c;
	}

	public String getD() {
		return this.d;
	}

	public void setD(String d) {
		this.d = d;
	}

	public Date getSavetime() {
		return this.savetime;
	}

	public void setSavetime(Date savetime) {
		this.savetime = savetime;
	}

	public Set getTbComments() {
		return this.tbComments;
	}

	public void setTbComments(Set tbComments) {
		this.tbComments = tbComments;
	}

	public Set getTbUsertitles() {
		return this.tbUsertitles;
	}

	public void setTbUsertitles(Set tbUsertitles) {
		this.tbUsertitles = tbUsertitles;
	}

}
