package com.gwytest.entity;
// Generated 2016-5-5 2:54:23 by Hibernate Tools 3.4.0.CR1


/**
 * TbUsertitle generated by hbm2java
 */
public class TbUsertitle implements java.io.Serializable {

	private int usertitleid;
	private TbTitle tbTitle;
	private TbUser tbUser;
	private int flag1;
	private int flag2;
	private int flag3;

	public TbUsertitle() {
	}
	public int getUsertitleid() {
		return this.usertitleid;
	}

	public void setUsertitleid(int usertitleid) {
		this.usertitleid = usertitleid;
	}

	public TbTitle getTbTitle() {
		return this.tbTitle;
	}

	public void setTbTitle(TbTitle tbTitle) {
		this.tbTitle = tbTitle;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}
	public int getFlag1() {
		return flag1;
	}
	public void setFlag1(int flag1) {
		this.flag1 = flag1;
	}
	public int getFlag2() {
		return flag2;
	}
	public void setFlag2(int flag2) {
		this.flag2 = flag2;
	}
	public int getFlag3() {
		return flag3;
	}
	public void setFlag3(int flag3) {
		this.flag3 = flag3;
	}


}
